### ISSUE TITLE
Please update to Redux 1.0 API 

### ISSUE THREAD

**Issue by gaearon** [Kvoti/redux-rest#1]
The code seems to be using Redux 0.12 but we are releasing 1.0 very soon with a slightly different API.
Please update to 1.0 RC so you can transition smoothly.

**Comment by mallison** [comment]
Thanks. Updating now. Oh I see I need to write/use a middleware now to handle async. Will investigate.

**Comment by mallison** [comment]
Nice, didn't have to change my code other than to bundle a tiny middleware (copied from redux docs) to handle action functions that launch async requests.

Updated README to reflect redux 1.0.0-rc API.

Added a test to make sure things _actually_ work with redux.
