### ISSUE TITLE
How do I set custom header?

### ISSUE THREAD

**Issue by bhoomit** [Kvoti/redux-rest#7]
I have an API request where I need to set custom header. How do I do that?

**Comment by mallison** [comment]
You can pass an options object to the ```Flux``` constructor (which I really must rename). One property is ```setCSRF``` which takes a function which is passed the request object, so you can set headers there (again that property could be named better). E.g

```js
function setHeaders(request) {
    request.set('Header', 'value');
    // you must return the request object (just realised this is a bug to fix too)
    return request;
}

const api = new Flux({
    setCSRF: setHeaders
});
```

(I wrote this library early on in my redux/flux days and, while it works, it needs some love to bring it up to standard)

Hope that helps.

**Comment by bhoomit** [comment]
Hi @mallison , thanks for responding :)

This is what I'm doing and its not working.

```
function setHeaders(request) {
      console.log('called')
      request.set('X-USER-ID', '1')
      // you must return the request object (just realised this is a bug to fix too)
      return request
  }

// Then create a Flux instance. This automatically creates
// action creators and reducers for each endpoint. No boilerplate!
const flux = new Flux({
  setCSRF: setHeaders,
  orders: '/api/orders/'
})
```

What am I doing wrong here?

**Comment by mallison** [comment]
No problem. It's entirely possibly it's my problem, not yours. I should be able to take a look this morning and see what's going on, as your code looks correct.

**Comment by bhoomit** [comment]
Cool. I'm also trying to understand how it works. Thanks!

**Comment by mallison** [comment]
I've had a quick look, and added a test to check the function you pass in can set headers. It seems to work. Are you looking at the request in your web server and not seeing the header? I'll try a real example to see if it works in the browser.

**Comment by mallison** [comment]
Stupid me. I didn't update the ```build``` dir when I published the last version. Will do that now. Sorry!

**Comment by mallison** [comment]
Updated to a new alpha release: please re-install and try again.

**Comment by bhoomit** [comment]
I was looking in Chrome Network window.

**Comment by mallison** [comment]
Have you tried the latest build now?

I merged the csrf stuff to master and updated the build so things should be
working.

**Comment by bhoomit** [comment]
Now the problem is, it doesn't get called in "GET" requests. I understood your code. Should I make that change?

**Comment by mallison** [comment]
Please do. Patches welcome ;). And apologies for the trouble. Though I'm glad someone is using it and finding these issues!

**Comment by bhoomit** [comment]
:) Happy to do it. If you have list of todos please post it in README. Will do if I find some time.

**Comment by mallison** [comment]
Great!

(One todo is actually a big rewrite now I'm a lot more experienced with redux, to make things feel more like redux)

**Comment by bhoomit** [comment]
Well I just started with Redux. So give me a week. Lets catch up after that.

**Comment by mallison** [comment]
No problem. Have fun!

**Comment by bhoomit** [comment]
How about I take out setCSRF outside and make it more generic like setHeaders? and have one generic method like prepareRequest which gets called before every request to add headers, CSRF, etc.

**Comment by mallison** [comment]
That's a good idea. So the default just sets the CSRF header, but the user
can pass in their own function to modify the request however they like.

**Comment by bhoomit** [comment]
Yes!
